# Generated by Django 6.0.3 on 2026-03-20 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
