# Generated by Django 6.0.3 on 2026-03-24 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contact_owner_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProceedingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Descrizione')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo procedimento',
                'verbose_name_plural': 'Tipi procedimento',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Fascicolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_title', models.CharField(blank=True, max_length=255)),
                ('custom_title', models.CharField(blank=True, max_length=255, verbose_name='Titolo personalizzato')),
                ('rg_number', models.CharField(blank=True, help_text='Numero di Registro Generale (es. 1234/2025)', max_length=50, verbose_name='RG')),
                ('court', models.CharField(blank=True, max_length=100, verbose_name='Tribunale')),
                ('status', models.CharField(choices=[('attivo', 'Attivo'), ('sospeso', 'Sospeso'), ('archiviato', 'Archiviato')], default='attivo', max_length=12, verbose_name='Stato')),
                ('opened_date', models.DateField(verbose_name='Data apertura')),
                ('first_hearing_date', models.DateField(blank=True, null=True, verbose_name='Prima udienza')),
                ('notes', models.TextField(blank=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fascicoli', to=settings.AUTH_USER_MODEL)),
                ('proceeding_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fascicoli', to='core.proceedingtype', verbose_name='Tipo procedimento')),
            ],
            options={
                'verbose_name': 'Fascicolo',
                'verbose_name_plural': 'Fascicoli',
                'ordering': ['-opened_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeadlineRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='Descrizione')),
                ('anchor', models.CharField(help_text='Campo data del fascicolo usato come punto di riferimento (es. first_hearing_date)', max_length=50, verbose_name='Ancora')),
                ('offset_days', models.IntegerField(help_text="Positivo = dopo l'ancora, negativo = prima dell'ancora", verbose_name='Scostamento (giorni)')),
                ('reminder_days_before', models.JSONField(default=list, help_text='Es. [7, 3, 1]', verbose_name='Promemoria (giorni prima)')),
                ('is_active', models.BooleanField(default=True)),
                ('proceeding_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='core.proceedingtype')),
            ],
            options={
                'verbose_name': 'Regola scadenza',
                'verbose_name_plural': 'Regole scadenze',
                'ordering': ['anchor', 'offset_days'],
            },
        ),
        migrations.CreateModel(
            name='FascicoloParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('assistito', 'Assistito'), ('controparte', 'Controparte'), ('avvocato_controparte', 'Avvocato di controparte'), ('consulente_tecnico', 'Consulente tecnico'), ('giudice', 'Giudice'), ('altro', 'Altro')], max_length=30, verbose_name='Ruolo')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fascicolo_roles', to='core.contact')),
                ('fascicolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='core.fascicolo')),
            ],
            options={
                'verbose_name': 'Parte del fascicolo',
                'verbose_name_plural': 'Parti del fascicolo',
                'unique_together': {('fascicolo', 'contact', 'role')},
            },
        ),
    ]
