# Generated by Django 6.0.3 on 2026-03-24 22:21

from django.db import migrations, models

CONTACT_ROLE_MAP = {
    'cliente': 'client',
    'controparte': 'opposing_party',
    'avvocato': 'lawyer',
    'consulente': 'consultant',
}


def migrate_contact_roles_forward(apps, schema_editor):
    Contact = apps.get_model('core', 'Contact')
    for old, new in CONTACT_ROLE_MAP.items():
        Contact.objects.filter(role=old).update(role=new)


def migrate_contact_roles_backward(apps, schema_editor):
    Contact = apps.get_model('core', 'Contact')
    for old, new in CONTACT_ROLE_MAP.items():
        Contact.objects.filter(role=new).update(role=old)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_fascicolo_proceeding_types'),
    ]

    operations = [
        # Backfill Contact.role values before updating the field definition.
        migrations.RunPython(
            migrate_contact_roles_forward,
            reverse_code=migrate_contact_roles_backward,
        ),
        migrations.AlterField(
            model_name='contact',
            name='role',
            field=models.CharField(choices=[('client', 'Cliente'), ('opposing_party', 'Controparte'), ('lawyer', 'Avvocato'), ('consultant', 'Consulente')], default='client', max_length=20),
        ),
        migrations.AlterField(
            model_name='deadlinerule',
            name='anchor',
            field=models.CharField(help_text='Name of the date field on Fascicolo used as the reference point (e.g. first_hearing_date)', max_length=50, verbose_name='Ancora'),
        ),
        migrations.AlterField(
            model_name='fascicolo',
            name='status',
            field=models.CharField(choices=[('active', 'Attivo'), ('suspended', 'Sospeso'), ('archived', 'Archiviato')], default='active', max_length=12, verbose_name='Stato'),
        ),
        migrations.AlterField(
            model_name='fascicoloparty',
            name='role',
            field=models.CharField(choices=[('client', 'Assistito'), ('opposing_party', 'Controparte'), ('opposing_counsel', 'Avvocato di controparte'), ('expert_witness', 'Consulente tecnico'), ('judge', 'Giudice'), ('other', 'Altro')], max_length=20, verbose_name='Ruolo'),
        ),
    ]
