# Generated by Django 6.0.3 on 2026-03-27 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_choice_keys_to_english'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('activity_type', models.CharField(choices=[('udienza', 'Udienza'), ('studio', 'Studio'), ('redazione', 'Redazione atti'), ('corrispondenza', 'Corrispondenza'), ('consulenza', 'Consulenza'), ('telefonate', 'Telefonate'), ('riunione', 'Riunione'), ('altro', 'Altro')], max_length=20, verbose_name='Tipo')),
                ('dm55_phase', models.CharField(choices=[('studio', 'Fase di studio'), ('introduttiva', 'Fase introduttiva'), ('istruttoria', 'Fase istruttoria'), ('decisionale', 'Fase decisionale')], max_length=15, verbose_name='Fase DM55')),
                ('duration_hours', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Durata (ore)')),
                ('notes', models.TextField(blank=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fascicolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.fascicolo')),
            ],
            options={
                'verbose_name': 'Attività',
                'verbose_name_plural': 'Attività',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
