# Generated by Django 6.0.3 on 2026-03-27 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='Descrizione')),
                ('due_date', models.DateField(verbose_name='Data scadenza')),
                ('source', models.CharField(choices=[('manual', 'Manuale'), ('template', 'Da tipo procedimento'), ('extracted', 'Estratta da atto')], max_length=10, verbose_name='Origine')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Completata')),
                ('notes', models.TextField(blank=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fascicolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='core.fascicolo')),
            ],
            options={
                'verbose_name': 'Scadenza',
                'verbose_name_plural': 'Scadenze',
                'ordering': ['is_completed', 'due_date'],
            },
        ),
    ]
